### ISSUE TITLE
baidu.dom.show在通过css样式隐藏时不起效果

### ISSUE THREAD

**Issue by nwind** [BaiduFE/Tangram-base#8]
create一个判断不会死的，N年的问题了，记录一下。。。性能根本不是问题，一般都只作用在最上层的节点上，浏览器中render tree的改动导致重新layout才是最耗时的

**Comment by leeight** [comment]
顶一下吧

**Comment by CatChen** [comment]
This is a really old problem! It deserved a solution.

**Comment by jkisjk** [comment]
悄悄的问句：为什么cat的回答不够本土化。

**Comment by CatChen** [comment]
Because I'm the one who's working on globalization instead of localization...

**Comment by cnberg** [comment]
发现show方法完全是一个jq发明的鸡肋，YUI和mootools没有这个方法，google closure实现了一个showElement方法，和tangram的show＋hide实现方式一样。不过他的注释写的很详细：

<pre>
/**
 * Shows or hides an element from the page. Hiding the element is done by
 * setting the display property to "none", removing the element from the
 * rendering hierarchy so it takes up no space. To show the element, the default
 * inherited display property is restored (defined either in stylesheets or by
 * the browser's default style rules.)
 *
 * Caveat 1: if the inherited display property for the element is set to "none"
 * by the stylesheets, that is the property that will be restored by a call to
 * showElement(), effectively toggling the display between "none" and "none".
 *
 * Caveat 2: if the element display style is set inline (by setting either
 * element.style.display or a style attribute in the HTML), a call to
 * showElement will clear that setting and defer to the inherited style in the
 * stylesheet.
 * @param {Element} el Element to show or hide.
 * @param {*} display True to render the element in its default style,
 * false to disable rendering the element.
 */
</pre>


结论：增加show和hide的注释，对于一些特殊情况，推荐使用setStyle而不是show or ihde。
