### ISSUE TITLE
文档中的小问题

### ISSUE THREAD

**Issue by jaypei** [BaiduFE/Tangram-base#84]
在Base文档中，baidu.array.empty的使用方法是这么写的：

```
var input = [1,"中文",4,5];
var output;
output = baidu.array.empty(input);
document.write("output: " + output+"<br>");
```

从源码中看empty没有返回值，只是把input给清空了。
http://tangram.baidu.com/tangram/baidu_array_empty.html

**Comment by cnberg** [comment]
已经修复，谢谢jaypei~
